### PR TITLE
- Fix the right lib where zfs_cmd_t structure is declared.

### PR DESCRIPTION
**Pull request by araujobsd**
- Declare the define ZFS_ONLINE_EXPAND.

Fix the issues related on iocage/iocage#297

Also built it on FreeBSD: 1101001 and 1200030

### CODE REVIEW

**Comment by joachimmathes** [comment]
:+1: Compiles on my FreeBSD 11.0-RELEASE-p11.

**Comment by gronke** [comment]
Works for me as well 👍

**Comment by rexpo** [comment]
Works for me here as well. On `10.3-RELEASE-p20` I can now compile with Cython 0.26!

**Comment by matias-pizarro** [comment]
This commit fixed the issue for me on 11.1-RELEASE-p1

**Review by kmoore134 — APPROVED** [review]
LGTM!

**Review by william-gr — APPROVED** [review]

**Comment by gronke** [comment]
@araujobsd Would be nice if you file a PR against jceel/py-libzfs as well.

**Comment by william-gr** [comment]
I disagree, jceel/py-libzfs is no longer actively maintaining it and freenas/py-libzfs is what is used in freebsd ports.

**Comment by araujobsd** [comment]
The official repository now is this one under FreeNAS!  I will update ports soon too.

**Comment by gronke** [comment]
I was referring to this comment https://github.com/iocage/iocage/issues/153#issuecomment-310528483 - I think Pull-Requests are still welcome, even though FreeNAS is running a fork. @araujobsd if you don't mind, I will cherry-pick your changes and create a PR myself

**Comment by william-gr** [comment]
The reality is that py-libzfs was developed under freenas and then it got moved away from one of the developers who left. I think we should treat freenas/py-libzfs as the main repo, not a fork.

**Comment by matias-pizarro** [comment]
Apart from the question of which is the ports source, it would be nice (and good practice) to submit to pypi so it can be installed with pip. It would mean using a library name that is not already taken (libzfs). Hijacking a pre-existing name, however stale the original lib, can only lead to confusion as this module gains popularity, as we all hope it will.

If you need help with pypi, just let me know

**Pull request merged**
